### ISSUE TITLE
ReferenceError: window is not defined on Next.js

### ISSUE THREAD

**Issue by ezeev** [LIQNFT/candy-shop#327]
There's a few places where the window object is being referenced:

https://github.com/LIQNFT/candy-shop/search?q=%22window.%22

This is breaking Next.js apps (we are using SSR) and there's no easy way to fix this without hacks. I think this could be solved in the library by adding checks to make sure `window` is defined?

**Comment by ezeev** [comment]
I found workaround for this for now using a combination of useState and useEffect:

```
  const [shop, setShop] = React.useState<JSX.Element | undefined>(undefined);

  React.useEffect(() => {
  
    import("@liqnft/candy-shop")
      .then((Candy) => {
        setShop(
          <Candy.CandyShopDataValidator>
            <Candy.Orders
              candyShop={candyShop}
              wallet={wallet}
              walletConnectComponent={<WalletMultiButton />}
              search
            />
          </Candy.CandyShopDataValidator>
        );
      })
      .catch((err) => void err);
    //}
  }, []);
```

**Comment by ezeev** [comment]
Note: the workaround I posted above works in dev environments but breaks typescript builds. Not a long-term solution.

**Comment by RustySol** [comment]
We have a community member who got a NextJs version working fine. Will post the link here when it's up

**Comment by RustySol** [comment]
Hi @ezeev, the NextJS repo is here for your ref
https://github.com/LIQNFT/candy-shop-storefront-nextjs
