### ISSUE TITLE
Transaction too large using custom SPL token

### ISSUE THREAD

**Issue by pbredenberg** [LIQNFT/candy-shop#78]
Hello! I've been trying out the project for the first time for that past couple of days. I've been able to get nfts listed so far, but when I try to purchase them with my custom SPL token, I get the following error `Transaction too large: 1267 > 1232`:

```
{err: Error: Transaction too large: 1267 > 1232
    at assert (http://localhost:1234/index.47330d7d.js:29…}
err: Error: Transaction too large: 1267 > 1232 at assert (http://localhost:1234/index.47330d7d.js:293038:27) at Transaction._serialize (http://localhost:1234/index.47330d7d.js:293408:9) at Transaction.serialize (http://localhost:1234/index.47330d7d.js:293389:21) at sendTx (http://localhost:1234/index.47330d7d.js:282880:102) at async buyAndExecuteSale (http://localhost:1234/index.47330d7d.js:282858:29) at async CandyShop.buy (http://localhost:1234/index.47330d7d.js:283006:24)
message: "Transaction too large: 1267 > 1232"
stack: "Error: Transaction too large: 1267 > 1232\n    at assert (http://localhost:1234/index.47330d7d.js:293038:27)\n    at Transaction._serialize (http://localhost:1234/index.47330d7d.js:293408:9)\n    at Transaction.serialize (http://localhost:1234/index.47330d7d.js:293389:21)\n    at sendTx (http://localhost:1234/index.47330d7d.js:282880:102)\n    at async buyAndExecuteSale (http://localhost:1234/index.47330d7d.js:282858:29)\n    at async CandyShop.buy (http://localhost:1234/index.47330d7d.js:283006:24)"
[[Prototype]]: Object
[[Prototype]]: Object
```

The store is on mainnet-beta

Here's my config:

```
// publickKey.ts
export const CREATOR_ADDRESS = '4AQHWYvT647XtdoW7KcVzjEwG3ZqmMDhBpZ316yJWrTp';
export const TREASURY_MINT = 'DKzkt1r6QctnQFx5hMnGomcMimXqVfAyBhMcoKHcBiNK';

// CandyShopContent.tsx
{
        currencySymbol: '$ROUNDIE',
        currencyDecimals: 0,
        priceDecimals: 0,
        volumeDecimals: 1
}
```

And here's my fork of this project with this behavior: https://github.com/the-roundies/candy-shop

Any clues as to what might be going wrong?

**Comment by RustySol** [comment]
@pbredenberg 
I think it's because there are too many tokens accounts that requires initiation in one single tx, as your NFT has 4 creators.
It should be easily fixable, but would like to get more details. Would you mind  joining our Discord at https://discord.gg/uDPYHs6Q and open a ticket from there? Thanks

**Comment by pbredenberg** [comment]
> @pbredenberg I think it's because there are too many tokens accounts that requires initiation in one single tx, as your NFT has 4 creators. It should be easily fixable, but would like to get more details. Would you mind joining our Discord at https://discord.gg/uDPYHs6Q and open a ticket from there? Thanks

Great! Will do, thank you!
