### ISSUE TITLE
try ti buy a nft ,it still show Processing purchase...

### ISSUE THREAD

**Issue by jackbbhua** [LIQNFT/candy-shop#88]
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/4037703/163832527-d232c063-24fe-4d09-97b5-5ea5865eed32.png">

i am try to testing buy a nft at https://candy.liqnft.com/marketplace. and my local martplace staill same. it shows Processing purchase... always.

**Comment by RustySol** [comment]
Hi @jackbbhua 
it's because solana devnet is down at the moment.

**Comment by RustySol** [comment]
For future reference.
https://explorer.solana.com/?cluster=devnet
if the transaction stats section shows 0 tx then means it's down

**Comment by jackbbhua** [comment]
> For future reference. https://explorer.solana.com/?cluster=devnet if the transaction stats section shows 0 tx then means it's down

if it is possible to custom the Transaction Fees of my store?
